### ISSUE TITLE
How to insert text?

### ISSUE THREAD

**Issue by DogLooksGood** [tbanel/uniline#4]
I don't know if it's the expected behavior, but after inserting a character, the cursor doesn't move.

**Comment by tbanel** [comment]
Yes, this is the current expected behavior.
The rational is that `uniline-mode` behave the same in north-south-east-west directions. Therefore moving the cursor east side is somehow arbitrary.

However this may surprise most users.

Moreover, this goes against the assumption that `uniline-mode` leaves as much features possible from the underlying major and minor modes. It also confuses `electric-pair-mode` (an issue is opened about that). And maybe it could confuse other unrelated utilities.

Therefore, I am working on changing that. Hopefully, inserting a character (and any other editing facilities) will give the same result as if `uniline-mode` was off.

Stay tuned and have fun

**Comment by yibie** [comment]
I have a suggestion:

After activating unline-mode, enable a temporary buffer. Once drawing is completed in the temporary buffer, insert it back into the original buffer.

**Comment by tbanel** [comment]
Hi @yibie!

You can certainly do that on top of `uniline-mode` if you need this workflow. Hereafter is the beginning of such a function:

```lisp
(defun uniline-in-temporary-buffer ()
  (interactive)
  (switch-to-buffer-other-window "*temp uniline*")
  (uniline-mode 1)  ;; ◀──── just switch uniline on
  … code to insert back …)
```

`uniline-mode` was designed to add drawing capabilities to whatever you are working on.
- Maybe you want to clarify a comment on an algorithm in a Python or C++ file with some arrows,
- Or you may draw boxes around some existing text in an Org Mode document,
- Or perhaps you need to enhance the documentation of a command line.

`uniline-mode` is designed to be intertwined with your current main work. And to get out of the way when no longer needed. It tries to not disturb your workflow.

**Comment by tbanel** [comment]
The change is done and committed!

Now ordinary characters move the cursor as usual.

Note that under `uniline-mode`, the `overwrite-mode` is active.

Within a few hours, Melpa will have packaged `uniline-mode` ready for upgrade.

Thanks @DogLooksGood for your feedback!
I close the issue. Do not hesitate to re-open it or a new one in case of something.

Have fun!

**Comment by DogLooksGood** [comment]
Yeah, it works now! 

I have a question, why we don't keep the overwrite mode, so input characters doesn't break the graph?
